vim.keymap.set("n", "<Esc>", "<cmd>nohlsearch<CR>", { noremap = true, silent = true })
vim.keymap.set("n", "gl", vim.diagnostic.open_float, { desc = "Show diagnostic message" })
vim.keymap.set("n", "]d", vim.diagnostic.goto_next, { desc = "Next diagnostic" })
vim.keymap.set("n", "[d", vim.diagnostic.goto_prev, { desc = "Previous diagnostic" })
vim.keymap.set("n", "<leader>q", vim.diagnostic.setloclist, { desc = "Open diagnostic [Q]uickfix list" })
vim.keymap.set("t", "EE", "<C-\\><C-n>", { desc = "Exit terminal mode" })

vim.keymap.set("n", "<leader>v", ":vsplit<CR>", { noremap = true, silent = true, desc = "Vertical split" })
vim.keymap.set("n", "<leader>d", ":split<CR>", { noremap = true, silent = true, desc = "Horizontal split" })
vim.keymap.set("n", "<leader>h", "<C-w>h", { desc = "Move focus to the left window" })
vim.keymap.set("n", "<leader>j", "<C-w>j", { desc = "Move focus to the lower window" })
vim.keymap.set("n", "<leader>k", "<C-w>k", { desc = "Move focus to the upper window" })
vim.keymap.set("n", "<leader>l", "<C-w>l", { desc = "Move focus to the right window" })
vim.keymap.set("n", "<leader>x", "<C-w>c", { noremap = true, silent = true, desc = "Close current split" })

vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv", { desc = "Move selection down", noremap = true, silent = true })
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv", { desc = "Move selection up", noremap = true, silent = true })

vim.keymap.set("n", "fj", "<cmd>b#<CR>", { noremap = true, silent = true, desc = "Switch between recent files" })
vim.keymap.set("n", "<leader>w", ":bd<CR>", { noremap = true, silent = true, desc = "Close buffer" })
vim.keymap.set("n", "<leader>e", ":Ex<CR>", { noremap = true, silent = true, desc = "Open netrw (:Ex)" })
vim.keymap.set("n", "<leader>u", "<cmd>UndotreeToggle<CR>", { noremap = true, silent = true, desc = "Toggle undotree" })

vim.keymap.set("i", "jj", "<Esc>")
vim.keymap.set("i", "<C-k>", vim.lsp.buf.signature_help, { desc = "Signature help" })
vim.keymap.set({ "n", "i", "v" }, "<C-s>", "<cmd>w<CR>", { desc = "Save file" })
